### ISSUE TITLE
Problem with multibyte characters

### ISSUE THREAD

**Issue by MHellmund** [PumasAI/QuartoNotebookRunner.jl#130]
I am testing a quarto project of 'book' type with the new julia engine.
Three times in about 50 pdf output pages it happened that a german umlaut ä,ü gets replaced by '��' (two copies of
the unicode replacement character U+fffd).

How to reproduce: 
Run `quarto render test3.qmd --to html` with the attached file. 

- It doesn't happen with jupter/IJulia.
- It doesn't happen with `QuartoNotebookRunner.run!(server, "test3.qmd"; output = "test3.ipynb")`
- Running quarto with `keep-md:true`, the '��'  are already in the `test3.html.md` file which is fed to pandoc.

My guess is that somewhere a string/buffer is cut in the middle of an utf8 multibyte character and then both parts are themselves interpreted as utf8 strings. So the invalid utf8 bytes get replaced by  U+fffd.

[test3.qmd.txt](https://github.com/PumasAI/QuartoNotebookRunner.jl/files/15306906/test3.qmd.txt)
[test3.html.md.txt](https://github.com/PumasAI/QuartoNotebookRunner.jl/files/15306941/test3.html.md.txt)

**Comment by jkrumbiegel** [comment]
the first place I can think of where a string is concatenated is in the quarto code that receives the message from the server in multiple parts https://github.com/quarto-dev/quarto-cli/blob/main/src/execute/julia.ts#L621-L633

**Comment by MHellmund** [comment]
the jupyter engine basically does the same thing https://github.com/quarto-dev/quarto-cli/blob/main/src/execute/jupyter/jupyter-kernel.ts#L103-L111

so maybe the sender is responsible and should send complete characters?

**Comment by jkrumbiegel** [comment]
probably the receiver, if the byte buffer slices weren't stringified, one wouldn't get these invalid chars first

<img width="575" alt="image" src="https://github.com/PumasAI/QuartoNotebookRunner.jl/assets/22495855/739e9f0e-58aa-441d-a44c-87b685fbb8c1">

**Comment by MHellmund** [comment]
here is my (tested) fix: 
https://github.com/MHellmund/quarto-cli/commit/7e313bedfe77ced2f822f9ee9d48dc533c6f5932
Please review it.

**Comment by MHellmund** [comment]
Thanks for the review. I'm really no javascript expert either.   I lowered the number of array allocations, use an array of arrays and use the array.set() method.  This is  according to https://stackoverflow.com/questions/10100798/whats-the-most-straightforward-way-to-copy-an-arraybuffer-object the fastest way to copy array parts and to flatten an array of arrays. 

here is the new patch: https://github.com/quarto-dev/quarto-cli/compare/main...MHellmund:quarto-cli:juliabug

**Comment by MichaelHatherly** [comment]
Fixed upstream, right @MHellmund? Reopen if needed.
