### ISSUE TITLE
Small difference to Jupyter/IJulia: `InteractiveUtils` not preloaded

### ISSUE THREAD

**Issue by MHellmund** [PumasAI/QuartoNotebookRunner.jl#142]
Unlike the jupyter engine or Julia REPL, code  like
```
 subtypes(Signed)
 @code_warntype(sin(1))
 @which sin
 methodswith(Vector)
```
needs an explicit `using InteractiveUtils`.
Should this be documented  somewhere?

**Comment by jkrumbiegel** [comment]
I don't have a strong opinion on this, either option could be reasoned for, @MichaelHatherly how about you?

**Comment by MichaelHatherly** [comment]
Yes, `InteractiveUtils` should be an implicit import, since all the other notebook envs and the REPL do it. No point being different with this detail.
