### ISSUE TITLE
Consider removing double quotes from strings interpolated into a document

### ISSUE THREAD

**Issue by jkrumbiegel** [PumasAI/QuartoNotebookRunner.jl#152]
I just tried an example workflow with parameters, and it seems to me this behavior is a bit impractical:

````
---
engine: julia
params:
    title: Title
    text: Text
    image: path to an image
---

# `{julia} title`

This is parametric text: `{julia} text`

And this is an image:

![Some image](`{julia} image`)

````

invoked with some parameters:

```
quarto render params.qmd -P title:"Custom title" -P text:"Some custom text" -P image:"surface.png"
```

Gives the following result:

<img width="654" alt="image" src="https://github.com/PumasAI/QuartoNotebookRunner.jl/assets/22495855/f98257cd-f168-4fa5-b445-fa9e63a43175">

`String`s in Julia have two different printing behaviors, `print` shows them without quotes and `show(io, MIME"text/plain"(), ...` adds them, so they can be entered back in from the copied output. I think this representation is not useful for inline evaluation. We can add `Text` around all values to make it work, but that's an unnecessary workaround:

````
---
engine: julia
params:
    title: Title
    text: Text
    image: path to an image
---

# `{julia} Text(title)`

This is parametric text: `{julia} Text(text)`

And this is an image:

![Some image](`{julia} Text(image)`)
````

<img width="828" alt="image" src="https://github.com/PumasAI/QuartoNotebookRunner.jl/assets/22495855/0bba6fcb-899d-43b0-8b76-a9cdaaecadf7">

**Comment by MichaelHatherly** [comment]
Agreed. My question is then do we special case `String`s or do we `print` every value when in inline rather than `show`ing them?

**Comment by MichaelHatherly** [comment]
And the other obvious question is what the other backends do here?

**Comment by jkrumbiegel** [comment]
I would say if it's has MIME `text/markdown`, insert as is, if it's not, `print` it to a string to markdown-escape it and then insert it?

> And the other obvious question is what the other backends do here?

Was just going to check. This is python:

````
```{python}
#| tags: [parameters]
#| 
title = "Title"
text = "Text"
image = "path to an image"
```

# `{python} title`

This is parametric text: `{python} text`

And this is an image:

![Some image](`{python} image`)
````

<img width="871" alt="image" src="https://github.com/PumasAI/QuartoNotebookRunner.jl/assets/22495855/b1905e54-8190-46ed-8645-4d29f52bfcd8">

**Comment by jkrumbiegel** [comment]
And here's knitr:

````
---
engine: knitr
params:
    title: Title
    text: Text
    image: path to an image
---


# `{r} params$title`

This is parametric text: `{r} params$text`

And this is an image:

![Some image](`{r} params$image`)

```r
"some string"
```
````

<img width="879" alt="image" src="https://github.com/PumasAI/QuartoNotebookRunner.jl/assets/22495855/ef6db47e-46b5-4be3-ba11-60756003f6fe">

**Comment by MichaelHatherly** [comment]
> I would say if it's has MIME text/markdown, insert as is, if it does not, print it to a string to markdown-escape it and then insert it?

Seems reasonable behaviour.

**Comment by jkrumbiegel** [comment]
Ah actually that would just be calling `string` on the values. As `string` is defined as the output of `print` as a `String`.
