### ISSUE TITLE
Engine not able to be set project-wide

### ISSUE THREAD

**Issue by alecloudenback** [PumasAI/QuartoNotebookRunner.jl#156]
After upgrading Julia, it seems that Quarto doesn't find the new binary?

I recently `juliaup` updated Julia from 1.10.3 to 1.10.4. After upgrading (the first time since using `engine: Julia`), running `quarto preview` I get the following error:

```

Starting julia-1.10 kernel...2024-06-19 09:36:21,342 - traitlets - ERROR - Failed to run command:
['/Users/alec/.julia/juliaup/julia-1.10.3+0.aarch64.apple.darwin14/bin/julia', '-i', '--color=yes', '--project=@.', '/Users/alec/.julia/packages/IJulia/Vo51o/src/kernel.jl', '/private/var/folders/ds/_tfd5bfd0bn51v_5xqxy821h0000gn/T/tmpx4rxy4rl.json']
    PATH='/Users/alec/.juliaup/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/TeX/texbin:/Applications/quarto/bin'
    with kwargs:
{'stdin': -1, 'stdout': None, 'stderr': None, 'cwd': '/Users/alec/prog/JuliaActuary.org/posts/fixed-effects', 'start_new_session': True}

2024-06-19 09:36:21,342 - traitlets - ERROR - [Errno 2] No such file or directory: '/Users/alec/.julia/juliaup/julia-1.10.3+0.aarch64.apple.darwin14/bin/julia'
Traceback (most recent call last):
  File "/Users/alec/.julia/conda/3/aarch64/lib/python3.10/site-packages/jupyter_client/manager.py", line 87, in wrapper
    out = await method(self, *args, **kwargs)
  File "/Users/alec/.julia/conda/3/aarch64/lib/python3.10/site-packages/jupyter_client/manager.py", line 439, in _async_start_kernel
    await self._async_launch_kernel(kernel_cmd, **kw)
  File "/Users/alec/.julia/conda/3/aarch64/lib/python3.10/site-packages/jupyter_client/manager.py", line 354, in _async_launch_kernel
    connection_info = await self.provisioner.launch_kernel(kernel_cmd, **kw)
  File "/Users/alec/.julia/conda/3/aarch64/lib/python3.10/site-packages/jupyter_client/provisioning/local_provisioner.py", line 210, in launch_kernel
    self.process = launch_kernel(cmd, **scrubbed_kwargs)
  File "/Users/alec/.julia/conda/3/aarch64/lib/python3.10/site-packages/jupyter_client/launcher.py", line 170, in launch_kernel
    raise ex
  File "/Users/alec/.julia/conda/3/aarch64/lib/python3.10/site-packages/jupyter_client/launcher.py", line 155, in launch_kernel
    proc = Popen(cmd, **kwargs)  # noqa
  File "/Users/alec/.julia/conda/3/aarch64/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/alec/.julia/conda/3/aarch64/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/alec/.julia/juliaup/julia-1.10.3+0.aarch64.apple.darwin14/bin/Julia'
```

I was using Quarto 1.5.43 and have now also tried Quarto ~1.4.45~ 1.5.45. I've also restarted shells and VS Code with no change.

My `_quarto.yml` file: https://github.com/JuliaActuary/JuliaActuary.org/blob/289a4440a6e1aa74101b0eeacd0e43250e256899/_quarto.yml

**Comment by MichaelHatherly** [comment]
Does it fail in the same way with just a simple notebook where you set `engine: julia` directly in the `.qmd`?

> and have now also tried Quarto 1.4.45

1.4 quarto doesn't support `engine: julia`. It needs the 1.5 pre-releases.

**Comment by alecloudenback** [comment]
Sorry, that was a typo. It was Quarto 1.5.45.

Putting the `engine: julia` in the page's front matter worked, and actually had a different message when starting:

```
Starting julia control server process. This might take a while...
Julia server process started.
```

Instead of 

```
Starting julia-1.10 kernel...
```

Which makes me think that the setting in the project's `_quarto.yml` was not being respected at all and had been using the IJulia kernel. 

Is this an issue with Quarto not recognizing the `engine: julia` or do I have my `_quarto.yml` set up incorrectly? I could not find any documentation on the appropriate place to put the `engine` setting in `_quarto.yml` and the `format`->`html` was the only section where the `engine: julia` entry did not error.

**Comment by MichaelHatherly** [comment]
> Which makes me think that the setting in the project's _quarto.yml was not being respected at all and had been using the IJulia kernel.

cc @jkrumbiegel on that one. Julius, not picking up `_quarto.yml` content hadn't been resolved yet had it?

**Comment by jkrumbiegel** [comment]
No, that's something they are aware of, but the issue has been open for a long time. It's only really become relevant with our engine, though. https://github.com/quarto-dev/quarto-cli/issues/3157

**Comment by alecloudenback** [comment]
Thanks for confirming that's the issue. I've created a PR here (#157 ) and in the Quarto docs (https://github.com/quarto-dev/quarto-web/pull/1171) noting this.
