### ISSUE TITLE
Support Quarto Projects

### ISSUE THREAD

**Issue by storopoli** [PumasAI/QuartoNotebookRunner.jl#16]
Quarto projects have a `_quarto.yml` and they have nice features:

* A way to render all or some of the files in a directory with a single command (e.g. `quarto render myproject`).
* A way to share YAML configuration across multiple documents.
* The ability to redirect output artifacts to another directory.
* The ability to freeze rendered output (i.e. don’t re-execute documents unless they have changed).

Reference: https://quarto.org/docs/projects/quarto-projects.html

**Comment by MichaelHatherly** [comment]
> The ability to freeze rendered output (i.e. don’t re-execute documents unless they have changed).

@storopoli any idea what the behaviour here is meant to be if a data source that is used in a notebook changes? Or if a project/manifest used in a notebook changes? Does this freezing only depend on qmd source itself?

**Comment by storopoli** [comment]
I think that it should track the `Project.toml`. Data, on the other hand I think is out of the scope of `quarto`, but I could be wrong.

**Comment by MichaelHatherly** [comment]
Yeah, that freeze behaviour appears to be pretty basic and does not consider data dependencies outside of the notebook if I'm reading it right. Perhaps that's fine, but also, it's not all that ideal, will result in stale notebooks down the line.

**Comment by MichaelHatherly** [comment]
> A way to render all or some of the files in a directory with a single command
> A way to share YAML configuration across multiple documents.

Probably covered by @jkrumbiegel's work on `quarto`, right? Or do you reckon we need anything else done here for that?

**Comment by jkrumbiegel** [comment]
As we ingest the project options sent by quarto in QuartoNotebookRunner now, parent project settings affect renders of qmd files as expected.

**Comment by MichaelHatherly** [comment]
Closing since this is dealt with by upstream `quarto` itself.
