### ISSUE TITLE
Seeded RNGs only work reproducibly within a cell

### ISSUE THREAD

**Issue by penelopeysm** [PumasAI/QuartoNotebookRunner.jl#192]
## Description

Calling `Random.seed!` at the top of a notebook doesn't ensure reproducibility of random number generation in other cells; it only works within the same cell that `seed!` is called.

I'm not sure if this is intentional, but it's slightly counterintuitive behaviour so if it's intentional it might be good to document it somewhere.

A related issue (and perhaps an example of how this behaviour is confusing!) is that the [Pumas tutorial on reproducibility](https://tutorials.pumas.ai/html/simulation/simulating_reproducible.html#local-reproducibility-setting-the-seed-inside-a-function-call) says that the second batch of samples in `Random.seed!(123); rand(3); rand(3)` should always result in "the same behavior [...] every time we run the code". This is true if done in a REPL, but the Quarto source has the second `rand(3)` in a different cell and consequently the second `rand(3)` will not always return the same numbers.

## MWE

The following notebook works to demonstrate the behaviour. The first call to randn() should always give the same result no matter how many times the notebook is rendered. The second call however will not.

````markdown
---
engine: julia
---

```{julia}
versioninfo()
```

```{julia}
using Random
Random.seed!(42)
randn()
```

```{julia}
randn()
```
````

## My `versioninfo` from the notebook above

```
Julia Version 1.10.5
Commit 6f3fdf7b362 (2024-08-27 14:19 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 10 × Apple M1 Pro
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, apple-m1)
Threads: 1 default, 0 interactive, 1 GC (on 8 virtual cores)
Environment:
  JULIA_LOAD_PATH = @:@stdlib
```

**Comment by devmotion** [comment]
I think this might be an upstream issue but I'm not too familiar with Malt so maybe it's intended and/or could be avoided:

```julia
julia> w = Malt.Worker();

julia> Malt.remote_eval_fetch(w, quote
           using Random
           Random.seed!(42)
           randn()
       end)
0.7883556016042917

julia> Malt.remote_eval_fetch(w, quote
           randn()
       end)
0.8653602653617717

julia> Malt.remote_eval_fetch(w, quote
           using Random
           Random.seed!(42)
           randn()
       end)
0.7883556016042917

julia> Malt.remote_eval_fetch(w, quote
           randn()
       end)
-0.6715764280647957
```

**Comment by MichaelHatherly** [comment]
Will investigate, thanks for the thorough issue description @penelopeysm.

**Comment by jkrumbiegel** [comment]
Maybe this has something to do with task-local RNG state? Could be that Malt evals in different tasks per fetch.

**Comment by devmotion** [comment]
Hmm, the RNG object id seems to be stable, so it seems to be the same RNG?
```julia
julia> Malt.remote_eval_fetch(w, quote
           objectid(Random.default_rng())
       end)
0xffffffff0968f0b4

julia> Malt.remote_eval_fetch(w, quote
           objectid(Random.default_rng())
       end)
0xffffffff0968f0b4

julia> Malt.remote_eval_fetch(w, quote
           objectid(Random.default_rng())
       end)
0xffffffff0968f0b4

julia> Malt.remote_eval_fetch(w, quote
           objectid(Random.default_rng())
       end)
0xffffffff0968f0b4
```

**Comment by jkrumbiegel** [comment]
I think that's because it's `TaskLocalRNG` and that's a singleton type:

```julia
julia> TaskLocalRNG() === TaskLocalRNG()
true
```

The RNG state for that is stored in the task itself.

**Comment by MichaelHatherly** [comment]
cc @fonsp in case you happen to have any insights.

**Comment by jkrumbiegel** [comment]
This shows that we get different task-local RNG state in a new `remote_eval_fetch`:

```julia
julia> Malt.remote_eval_fetch(w, quote
           using Random
           Random.seed!(123)

           rngfields = filter(fieldnames(Task)) do field
               startswith(string(field), "rng")
           end
           state = NamedTuple(map(rngfields) do field
               field => getfield(Base.current_task(), field)
           end)
       end)
(rngState0 = 0xfefa8d41b8f5dca5, rngState1 = 0xf80cc98e147960c1, rngState2 = 0x20e2ccc17662fc1d, rngState3 = 0xea7a7dcb2e787c01, rngState4 = 0xf4e85a418b9c4f80)

julia> Malt.remote_eval_fetch(w, quote
           rngfields = filter(fieldnames(Task)) do field
               startswith(string(field), "rng")
           end
           state = NamedTuple(map(rngfields) do field
               field => getfield(Base.current_task(), field)
           end)
       end)
(rngState0 = 0x4e291591396795b9, rngState1 = 0xc9a680b08b4c9006, rngState2 = 0x3bb5088d1c600f58, rngState3 = 0xe2bb063e7e800a67, rngState4 = 0xe264ff418d928577)
```

**Comment by jkrumbiegel** [comment]
If this is hard to fix in Malt, I guess we could store the `rngState` fields after a task runs a cell, and then first thing in the next cell, mutate that one's `rngState` fields so they take the same values. Not sure if Malt can be configured to use only a single task.

**Comment by devmotion** [comment]
Maybe one could take some inspiration from how Test resets the task-local RNG: https://github.com/JuliaLang/julia/blob/1438b1578941d0f1cc8f8c958cf3bd2927fd482c/stdlib/Test/src/Test.jl#L1694-L1720

**Comment by jkrumbiegel** [comment]
Interesting, it seems this looked quite different on 1.10 where `Random.get_tls_seed()` did not exist

https://github.com/JuliaLang/julia/blob/6f3fdf7b36250fb95f512a2b927ad2518c07d2b5/stdlib/Test/src/Test.jl#L1567-L1578

**Comment by fonsp** [comment]
@Pangoraw knows best about RNGs and threading in Pluto :)

**Comment by Pangoraw** [comment]
`remote_eval_fetch` indeed spawns a new task at each call. One solution would be for QuartoNotebookWorker to manage its own persistent task for evaluation and then communicate with this task using channels.

**Comment by devmotion** [comment]
The more I thought about this issue, the more I got the feeling that this is an upstream issue in Malt. The behaviour seems completely surprising, in particular given that everything else is consistent between subsequent `Malt.remote_eval_fetch` calls and there were not tasks involved in the to-be-evaluated expressions sent to the worker (additionally, in my example above the worker used a single thread). Additionally, it seemed the behaviour was not documented, so I assumed possibly it was not even intentional.

But then I tried the same example with Distributed:
```julia
julia> using Distributed

julia> addprocs(1)
1-element Vector{Int64}:
 2

julia> remotecall_fetch(eval, 2, quote
           using Random
           Random.seed!(42)
           randn()
       end)
0.7883556016042917

julia> remotecall_fetch(eval, 2, quote
           randn()
       end)
0.08641660475950964

julia> remotecall_fetch(eval, 2, quote
           using Random
           Random.seed!(42)
           randn()
       end)
0.7883556016042917

julia> remotecall_fetch(eval, 2, quote
           randn()
       end)
1.559594774368473

julia> remotecall_fetch(eval, 2, quote
           objectid(Base.current_task())
       end)
0xebc117a52ab2a7be

julia> remotecall_fetch(eval, 2, quote
           objectid(Base.current_task())
       end)
0xe14f2bb195cecba7
```

So it seems Malt is consistent with Distributed. I couldn't find any issue related to it in the Distributed repo but in the Julia repo someone had opened an issue regarding this behaviour: https://github.com/JuliaLang/julia/issues/51225 It also links to a Pluto issue: https://github.com/fonsp/Pluto.jl/issues/2290

So my take away is that the behaviour of Malt is consistent with Distributed but that this behaviour - both in Distributed and in Malt - is confusing and surprising for users. Based on the discussion in the Julia issue, I assume Distributed won't be changed - but since there are issues from both Pluto and Quarto users, maybe it could be addressed in Malt? Maybe Malt could expose an API for evaluations within a persistent task?

**Comment by jkrumbiegel** [comment]
I thought it would look something like this:

```julia
using Malt

function initialize_special_channels(worker)
    @assert Malt.remote_eval_fetch(worker, quote
        var"__special_channel_out" = Channel()
        var"__special_channel_in" = Channel{Expr}() do chan
            for expr in chan
                result = Core.eval(Main, expr)
                put!(var"__special_channel_out", result)
            end
        end
        true
    end)
end

function remote_eval_fetch_channeled(worker, expr::Expr)
    code = quote
        Threads.@spawn put!(var"__special_channel_in", $(QuoteNode(expr)))
        take!(var"__special_channel_out")
    end
    return Malt.remote_eval_fetch(worker, code)
end

w = Malt.Worker()
initialize_special_channels(w)
```

I do get consistent random numbers with this technique:

<img width="491" alt="image" src="https://github.com/user-attachments/assets/1ff06ab7-40a6-4065-80af-3981024393ff">

**Comment by MichaelHatherly** [comment]
> Should we go with that?

Sounds fine to me :+1:

**Comment by jkrumbiegel** [comment]
I'll attempt a PR

**Comment by fonsp** [comment]
Nice! Could you also make a PR to Malt to add this consistency as a test?

**Comment by jkrumbiegel** [comment]
> Nice! Could you also make a PR to Malt to add this consistency as a test?

@fonsp Wait I thought I'd implement this logic in QuartoNotebookRunner, did you think it was a good fit for Malt itself?

**Comment by fonsp** [comment]
No my suggestion is to add a **test** to Malt for this behaviour, to guarantee that this will continue working in future Malt versions, since you depend on it.

**Comment by jkrumbiegel** [comment]
To my understanding I'm not depending on anything new in Malt with this workaround, I'm depending on Julia's channel and task behavior. If you change your implementation some day to use a stable task for all evals then the workaround might not be necessary anymore but it shouldn't break.
