### ISSUE TITLE
Information about Quarto upstream issues 10034 and 3157

### ISSUE THREAD

**Issue by andreuvall** [PumasAI/QuartoNotebookRunner.jl#195]
I have been trying to render a toy Quarto project combining Quarto Markdown files (`.qmd`) and Julia scripts (`.jl`) annotated with the percent format. I have hit two Quarto upstream issues ([10034](https://github.com/quarto-dev/quarto-cli/issues/10034) and [3157](https://github.com/quarto-dev/quarto-cli/issues/3157)) which made it tricky for me to understand what was and wasn't possible at the moment. 

I have drafted an extended version of the "note" block at the beginning of the README file. It could make it easier for other users to understand the current situation. I can make a PR, if this reads like something that can be worked on.

> [!NOTE]
>
> This Julia package provides a code evaluation engine that Quarto 
> can use. Please run the `quarto` CLI tool rather than this package
> directly unless you would like to help with the development of this engine.
>
> Starting from the **pre-release** [`v1.5.29`](https://github.com/quarto-dev/quarto-cli/releases/tag/v1.5.29)
> this engine is available out-of-the-box with `quarto` when you set `engine: julia` in
> your Quarto Markdown files. You don't need to follow the developer instructions below. Note, however, the following Quarto upstream issues.
>
> #### [Scripts with the percent format](https://github.com/quarto-dev/quarto-cli/issues/10034)
> QuartoNotebookRunner can process Julia scripts annotated with the [percent format](https://jupytext.readthedocs.io/en/latest/formats-scripts.html#the-percent-format) (see this [`test file`](test/examples/cell_types.jl) for an example). However, at the moment, Quarto [mistakenly assigns the Jupyter engine](https://github.com/quarto-dev/quarto-cli/issues/10034#issuecomment-2174251544) as soon as the percent format is detected, even if the Julia engine is explicitly set in the script header. A somewhat unsatisfactory workaround is to move the code of interest to a Quarto Markdown file. Alternatively, it is still possible to render individual Julia scripts using QuartoNotebookRunner directly, as described in the [Usage](#usage) section below. Quarto projects including Julia scripts can not be rendered until the upstream issue is resolved.
>
> #### [Project-wide engine](https://github.com/quarto-dev/quarto-cli/issues/3157)
> If you are working with [Quarto Projects](https://quarto.org/docs/projects/quarto-projects.html), be aware that Quarto is failing to set a project-wide engine other than Python. A simple workaround is to set the Julia engine in each Quarto Markdown file of your project.

**Comment by MichaelHatherly** [comment]
> I can make a PR, if this reads like something that can be worked on.

Thanks. Sure, please open a PR.

**Comment by jkrumbiegel** [comment]
> If you are working with Quarto Projects, be aware that Quarto is failing to set a project-wide engine other than Python.

This is not quite true. Quarto completely disregards the engine key when it's set in the project file, as far as I know, it affects all languages (but python only has one backend, jupyter)

The rest looks good to me

**Comment by MichaelHatherly** [comment]
Fixed in #196.
