### ISSUE TITLE
Quarto Notebook not rendering

### ISSUE THREAD

**Issue by farmacyst99** [PumasAI/QuartoNotebookRunner.jl#222]
Hi, I'm using Pumas and need to use Quarto to prepare a document. But after giving the render command, the process gets stuck with no error or output. I'm trying to use the Julia engine. This is the output to ```quarto check```

```
quarto check
Quarto 1.6.39
[✓] Checking environment information...
      Quarto cache location: /Users/farmacyst/Library/Caches/quarto
[✓] Checking versions of quarto binary dependencies...
      Pandoc version 3.4.0: OK
      Dart Sass version 1.70.0: OK
      Deno version 1.46.3: OK
      Typst version 0.11.0: OK
[✓] Checking versions of quarto dependencies......OK
[✓] Checking Quarto installation......OK
      Version: 1.6.39
      Path: /Applications/quarto/bin

[✓] Checking tools....................OK
      TinyTeX: (not installed)
      Chromium: (not installed)

[✓] Checking LaTeX....................OK
      Tex:  (not detected)

[✓] Checking basic markdown render....OK

[✓] Checking Python 3 installation....OK
      Version: 3.9.6
      Path: /Library/Developer/CommandLineTools/usr/bin/python3
      Jupyter: (None)

      Jupyter is not available in this Python installation.
      Install with python3 -m pip install jupyter

[✓] Checking R installation...........OK
      Version: 4.4.2
      Path: /Library/Frameworks/R.framework/Resources
      LibPaths:
        - /Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library
      knitr: (None)
      rmarkdown: (None)

      The knitr package is not available in this R installation.
      Install with install.packages("knitr")
      The rmarkdown package is not available in this R installation.
      Install with install.packages("rmarkdown")
```

this is the front matter on the document:

```
---
title: "Untitled"
format: html
engine: julia
---

```

But as soon as I put ```quarto render filename``` I get no output or error. 

I have tried running ``` quarto render filename --execute-debug``` and get the following output:

```
quarto render brooks-model.qmd --execute-debug
- Transport file /Users/farmacyst/Library/Caches/quarto/julia/julia_transport.txt exists, reusing server.
- Transport file read successfully.
- Connecting to server at port 8000, pid 1577
- write command "isready" to socket server
- received server response
- Transport file read successfully.
- write command "run" to socket server

```

**Comment by MichaelHatherly** [comment]
> But as soon as I put `quarto render filename` I get no output or error.

Does it hang and never complete, or does it complete but just display nothing?

**Comment by farmacyst99** [comment]
Yes, it hangs and never completes.

Regards,
Abhimanyu

**Comment by MichaelHatherly** [comment]
> Yes, it hangs and never completes.

Is this dependent on whether you have `{julia}` cells in the document? Or does it also hang even when there are no cells in the document?

**Comment by farmacyst99** [comment]
I get the following output:

quarto render brooks-model.qmd --execute-debug


*- Transport file
/Users/farmacyst/Library/Caches/quarto/julia/julia_transport.txt exists,
reusing server.*

*- Transport file read successfully.*

*- Connecting to server at port 8000, pid 1577*

*- write command "isready" to socket server*

*- received server response*

*- Transport file read successfully.*

*- write command "run" to socket server*

^C*%*
      ***@***.*** pmx % kill $(ps aux | grep
'[j]ulia.*quartonotebookrunner\.jl' | awk '{print $2}')

***@***.*** pmx % quarto render brooks-model.qmd
--execute-debug

*- Transport file
/Users/farmacyst/Library/Caches/quarto/julia/julia_transport.txt exists,
reusing server.*

*- Transport file read successfully.*

*- Connecting to server at port 8000, pid 1577*

*- write command "isready" to socket server*





*- Connecting to server failed, a transport file was reused so it might be
stale. Delete transport file and retry.*

*- Transport file
/Users/farmacyst/Library/Caches/quarto/julia/julia_transport.txt doesn't
exist*

Starting julia control server process. This might take a while...

ERROR: NotFound: Failed to spawn 'julia': No such file or directory (os
error 2)


Stack trace:

    at spawnChildInner (ext:runtime/40_process.js:186:17)

    at spawnChild (ext:runtime/40_process.js:208:10)

    at Command.spawn (ext:runtime/40_process.js:480:12)

    at ensureQuartoNotebookRunnerEnvironment
(file:///Applications/quarto/bin/quarto.js:41209:26)

    at startOrReuseJuliaServer
(file:///Applications/quarto/bin/quarto.js:41120:19)

    at getJuliaServerConnection
(file:///Applications/quarto/bin/quarto.js:41233:30)

    at getJuliaServerConnection
(file:///Applications/quarto/bin/quarto.js:41263:26)

    at eventLoopTick (ext:core/01_core.js:214:9)

    at async executeJulia
(file:///Applications/quarto/bin/quarto.js:41292:18)

    at async Object.execute
(file:///Applications/quarto/bin/quarto.js:41037:20)

**Comment by MichaelHatherly** [comment]
> ERROR: NotFound: Failed to spawn 'julia': No such file or directory (os
error 2)

That is the important part, it appears there is no `julia` binary found. Does `julia` run in that same terminal start up Julia, or does that fail as well?

**Comment by MichaelHatherly** [comment]
> No it does not start up in the same terminal, but I have the Julia app
installed via their website

If it does not start up then there is a more fundamental issue beyond `QuartoNotebookRunner.jl` that needs to be resolved that is more related to PumasDesktop setup. Please continue the discussion over in https://discourse.pumas.ai/t/quarto-notebook-not-rendering/1092/11 where this begun.

**Comment by farmacyst99** [comment]
then do you think adding julia to the system variables would solve this
problem? or is there some other solution?

**Comment by MichaelHatherly** [comment]
Closing as this is Pumas-specific. Continuation of the discussion is in the discourse thread.
