### ISSUE TITLE
How to use julia in RStudio about qmd by QuartoNotebookRunner.jl ?

### ISSUE THREAD

**Issue by Liu23308** [PumasAI/QuartoNotebookRunner.jl#225]

**Comment by Liu23308** [comment]
```{julia}

1 + 2

```

Error in julia_setup() : Julia is not found.

**Comment by MichaelHatherly** [comment]
> Julia is not found

Are you able to run a normal `julia` REPL on your system?

**Comment by Liu23308** [comment]
> > Julia is not found
> 
> Are you able to run a normal `julia` REPL on your system?

Thank you for your reply. I can run julia code in julia REPL.

**Comment by jkrumbiegel** [comment]
We don't know where your mentioned function `julia_setup()` is from so it's impossible to say what's going on here. Please add more information that clearly specifies your workflow so we can try to reproduce it. Note also that we'll not be able to debug RStudio problems here so ideally you'd show some evidence like stacktraces etc. that the issue you're facing is related to QuartoNotebookRunner.jl and not a general problem setting up Julia, for example.

**Comment by Liu23308** [comment]
https://quarto.org/
For example, in RStudio, I use qmd.

---
title: "Untitled"
format: html
editor: visual
---

```{r}

c <- 2+3
c

```

[1] 5

```{python}

c = 2+3
c

```
5

```{julia}

c = 2+3
c

```

Error in julia_setup() : Julia is not found.

**Comment by jkrumbiegel** [comment]
If you don't specify `engine: julia` in the frontmatter you currently do not get the native Julia engine. Therefore your error is thrown by some other engine that quarto chooses when R, Python and Julia snippets are in the code. I assume that might be the knitr engine but I'm not sure. Either way, it's not about QuartoNotebookRunner so I'm going to close this issue.

Note that it's currently supported to add R code blocks to be executed via RCall with QuartoNotebookRunner, but not python code blocks.
