### ISSUE TITLE
Output options

### ISSUE THREAD

**Issue by devmotion** [PumasAI/QuartoNotebookRunner.jl#35]
I couldn't find any occurrence of e.g. `output: asis` in the source code of QuartoNotebookRunner, so I'm opening this issue to double check: Which of the output options listed in https://quarto.org/docs/computations/execution-options.html#output-options are currently supported?

**Comment by MichaelHatherly** [comment]
Yes, there isn't any specific handling of `asis`. Are any of the `output` options behaving incorrectly at the moment? If there is then we can just fix it here. It might just be something to we hand over to the `quarto render` to deal with without having to do anything further.

**Comment by MichaelHatherly** [comment]
Not actionable from the backend as far as I can tell. @devmotion if you notice any `output` option that isn't actually supported here then just report it here. Closing for now though.
