### ISSUE TITLE
Correctly handle `display` usage in cells

### ISSUE THREAD

**Issue by MichaelHatherly** [PumasAI/QuartoNotebookRunner.jl#37]

**Comment by MichaelHatherly** [comment]
> The question is if we want to make it work this way, or offer an alternative.

Probably just hooking into `display`, unless you can think of a nicer approach.

**Comment by jkrumbiegel** [comment]
can we currently add arbitrarily many outputs of a given MIME type to the ipynb we output?

> Probably just hooking into display

Yeah either that or with a special type `MultiOutput` or so that would need to be made available. I guess easier to do the `display` route

**Comment by MichaelHatherly** [comment]
> Yeah either that or with a special type MultiOutput or so that would need to be made available.

Yes, that's an option, though if a user evals a single cell into a REPL they'll not have that type defined, which would probably be annoying.

Just following what IJulia does is probably the most straightforward thing to do currently.
