### ISSUE TITLE
Support worker timeout

### ISSUE THREAD

**Issue by jkrumbiegel** [PumasAI/QuartoNotebookRunner.jl#38]
Quarto is set up so that keepalive session time out after a while, to save resources (otherwise these worker processes would just hang around forever and we all know that julia is not the most lightweight process). We currently don't support this.

**Comment by MichaelHatherly** [comment]
> session time out after a while

Is this a hardcoded value, or something that can be configured? What is the current value?

**Comment by jkrumbiegel** [comment]
It appears to be 300 seconds by default (which we ignore) and you can override it https://quarto.org/docs/computations/julia.html#kernel-daemon

**Comment by jkrumbiegel** [comment]
implemented in #61
