### ISSUE TITLE
Multiple outputs per cell

### ISSUE THREAD

**Issue by jkrumbiegel** [PumasAI/QuartoNotebookRunner.jl#44]
I was copying quarto tests to use our native runner, and this failed:

````qmd
---
title: Julia Subfig Test
engine: julia
---

```{julia}
Pkg.activate(temp = true)
Pkg.add(name = "Plots", version = "1.40.1")
```

## Julia Crossref Figure

```{julia}
#| label: fig-plots
#| fig-cap: "Plots"
#| fig-subcap:
#|   - "Plot 1"
#|   - "Plot 2"
#| layout-ncol: 2

using Plots
plot([1,23,2,4]) |> display

plot([8,65,23,90]) |> display
```

See @fig-plots for examples. In particular, @fig-plots-2.
````

So they are using `display` twice to get a multi-column figure output. As we don't hook into the `display` system but only render return values, this does not work. The question is if we want to make it work this way, or offer an alternative.

**Comment by jkrumbiegel** [comment]
This is probably the same as https://github.com/PumasAI/QuartoNotebookRunner.jl/issues/37

**Comment by MichaelHatherly** [comment]
> This is probably the same as https://github.com/PumasAI/QuartoNotebookRunner.jl/issues/37

Yes, same as that one.
