### ISSUE TITLE
Support Julia REPL help mode

### ISSUE THREAD

**Issue by MHellmund** [PumasAI/QuartoNotebookRunner.jl#56]
With QuartoNotebookRunner 0.4.0,
 
     ```{julia}
     ?for
     ```
is a Julia parse error. It works for me with Quarto/IJulia: https://www.math.uni-leipzig.de/~hellmund/juliabook/chapters/first_contact.html#sec-tab

**Comment by MichaelHatherly** [comment]
It would be possible to support something like REPL modes most likely. Happy to accept PRs for this.

**Comment by MHellmund** [comment]
closed by https://github.com/PumasAI/QuartoNotebookRunner.jl/pull/121

**Comment by MHellmund** [comment]
closed by https://github.com/PumasAI/QuartoNotebookRunner.jl/pull/121
