### ISSUE TITLE
Support truncation of output of large data structures

### ISSUE THREAD

**Issue by MHellmund** [PumasAI/QuartoNotebookRunner.jl#57]
With QuartoNotebookRunner 0.4.0,

     ```{julia}
     v = rand(10^7)
     ```

produces $10^7$ output lines. IJulia truncates in a way similar to the REPL, see the third cell here:
https://www.math.uni-leipzig.de/~hellmund/juliabook/chapters/numerictypes.html#der-datentyp-bigint

**Comment by MichaelHatherly** [comment]
Thanks for reporting this @MHellmund.
