### ISSUE TITLE
Use `--project=@.` as default setting?

### ISSUE THREAD

**Issue by devmotion** [PumasAI/QuartoNotebookRunner.jl#66]
I think it would be convenient if QuartoNotebookRunner would use `--project=@.` as default setting for the worker processes. This would reduce the configuration (no `exeflags` needed) in many common cases and would match the behaviour of the default IJulia kernel: https://github.com/JuliaLang/IJulia.jl/blob/185533665803d5c0f9de6103d0c386422d9e1c6a/docs/src/manual/usage.md?plain=1#L18-L24

**Comment by MichaelHatherly** [comment]
Seems reasonable to me.

**Comment by jkrumbiegel** [comment]
We talked about this before, one alternative to `@.` was having a per-notebook project because like Pluto realized, notebooks are most reproducible if they don't interact with each other. But I'm also ok with `@.`. Better than the main env in any case.

**Comment by devmotion** [comment]
Yeah, IMO one of the great things about Pluto is how it handles Julia dependencies and one can ensure reproducibility without having to share a separate Project.toml + Manifest.toml. My gut feeling is that you can't guarantee reproducibility anymore anyway if Project.toml + Manifest.toml are stored in separate files - even if you specify (or even enforce from QuartoNotebookRunner) a specific project path: users always have to make sure that the toml files are in the right folder and per se there's no guarantee that the toml files are valid and consistent with the qmd file. So my feeling is that a default of `@.` is not actually worse with regards to reproducibility but on the other hand it is much more convenient than a specific (sub)folder when you have a collection/project of qmd files in a non-flat directory structure that mostly share a single project environment.
