### ISSUE TITLE
Differences to knitr

### ISSUE THREAD

**Issue by jkrumbiegel** [PumasAI/QuartoNotebookRunner.jl#70]
While I've been looking into options to implement https://github.com/PumasAI/QuartoNotebookRunner.jl/issues/65 I've noticed how knitr does a bunch of things slightly differently than the jupyter based quarto backends (which we are closer to in spirit because we render to an ipynb intermediate format).

One difference is how the ordering of outputs is handled. With the ipynb, one code cell has its code, its stdout/stderr output, and its MIME typed outputs. There is no ordering to them, though, as can be seen here:

````quarto
```{julia}
struct SVG end

Base.show(io::IO, ::MIME"image/svg+xml", s::SVG) = print(io, """
<?xml version="1.0"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.0//EN" 
              "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd">
<svg xmlns="http://www.w3.org/2000/svg">
  <style type="text/css">
    circle:hover {fill-opacity:0.9;}
  </style>
  <g style="fill-opacity:0.7;">
    <circle cx="6.5cm" cy="2cm" r="100" style="fill:red; stroke:black; stroke-width:0.1cm" transform="translate(0,50)" />
    <circle cx="6.5cm" cy="2cm" r="100" style="fill:blue; stroke:black; stroke-width:0.1cm" transform="translate(70,150)" />
    <circle cx="6.5cm" cy="2cm" r="100" style="fill:green; stroke:black; stroke-width:0.1cm" transform="translate(-70,150)"/>
  </g>
</svg>""")
```

```{julia}
println("a line")
display(SVG())
println("another line")
display(SVG())
```
````

<img width="439" alt="image" src="https://github.com/PumasAI/QuartoNotebookRunner.jl/assets/22495855/bea2e0c4-e0f8-443f-b7a2-4e0b2d279539">

With knitr, it works like this, which I somehow find superior:

````quarto
```{r}
cat("a line")
plot(c(1, 2, 3))
cat("another line")
plot(c(4, 5, 6))
```
````

<img width="656" alt="image" src="https://github.com/PumasAI/QuartoNotebookRunner.jl/assets/22495855/0858d77c-b888-405e-846a-0bb7136241d6">

The other big difference is that in knitr, you can interact with the knitting process directly. So you can `knit` some code into the document which gives you the opportunity to create multiple cells with arbitrary content dynamically, which is one way how people are implementing things like the aforementioned dynamic number of tabs.

Like this example, where the function `knit` is called below to turn the code generated on the fly into a part of the document. You couldn't do that in ipynb (not that I think this is necessarily a good interface, it is flexible though).

````
```{r}
out = NULL

for (i in 1:3) {
  knit_expanded <- paste0("\n```{r}\n\n1 + 1\n\n```");
  out = c(out, knit_expanded);
}
```

<!--- knit those table chunk statements --> 

```{r}
paste(knit(text = out), collapse = '\n')
```
````

So I am thinking about whether we want to stay with the ipynb approach, which in a way limits us (another problem we were facing was having multiple languages in one ipynb I think), or want to start rendering our own intermediate markdown, where we have all options to do whatever we want. This could make it easier for us to reach feature parity with knitr, which seems to be the most powerful and versatile quarto backend currently.

**Comment by vjd** [comment]
>This could make it easier for us to reach feature parity with knitr, which seems to be the most powerful and versatile quarto backend currently.

From the example you gave above as a context, we should consider this recommendation as a long-term goal. Just depends on how much work it is to maintain

**Comment by MHellmund** [comment]
For your first example, Jupyter + IJulia.jl generate a cell with 4 output subcells in the right order (with  output_type `stream`, `display_data`, `stream` , `display_data`) and the Quarto output is as you want it: all 4  subcells in the right order.

**Comment by jkrumbiegel** [comment]
I'm going to close this issue because we have the cell expansion mechanism now. I'm going to close a more focused issue about the cell ordering, as I wasn't aware that IJulia did this differently.
